#Q1. What is the total revenue generated by male vs. female customers?

USE customer_behavior;
SELECT gender, SUM(`Purchase Amount (USD)`) AS revenue
FROM customers
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?

USE customer_behavior;
SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customers
WHERE `Discount Applied` = 'Yes' 
  AND `Purchase Amount (USD)` >= (SELECT AVG(`Purchase Amount (USD)`) FROM customers)
  
#Q3. Which are the top 5 products with the highest average review rating


